#!/bin/bash
source lights.conf

SLEEPTIME=$(($TRANSTIME / 10))
SLEEPTIMELONG=$(($SLEEPTIME * 3))

light_bri $1 1
sleep 1

while true
do
    light_bri $1 254
    sleep $SLEEPTIME
    light_bri $1 1
    sleep $SLEEPTIMELONG
done
