#!/bin/bash

#acceptable values: 0 - 255

source lights.conf

URL=http://$HUEIP/api/$SECRET/groups/0/action
PAYLOAD='{"sat": '$1', "transitiontime": 0}'
curl -H "Accept: application/json" -X PUT --data "$PAYLOAD" $URL > /dev/null
