#!/bin/bash
source lights.conf
LIGHTNUM=$1

URL=http://$HUEIP/api/$SECRET/lights/$1/state
#PAYLOAD='{"hue": '$2', "transitiontime": 10}'
PAYLOAD='{"ct": '$((1000000/$2))', "transitiontime": '$TRANSTIME'}'


curl -s -H "Accept: application/json" -X PUT --data "$PAYLOAD" $URL > /dev/null
