#!/bin/bash
echo 

lights_bri_notrans 1
lights_sat_notrans 255
lights_hue_notrans 46920
sleep 1

while true
do
	#25500 + rnd(40000) is more cyber
    # col1=$[ 25500 + $[ RANDOM % 40000 ]]
    # col2=$[ 25500 + $[ RANDOM % 40000 ]]
    # col1=$[ 4000 + RANDOM % 16000 ]
    # col2=$[ 4000 + RANDOM % 16000 ]

    # $RANDOM only goes till 32768!!!
    col1=$[ $RANDOM + $RANDOM ]
    col2=$[ $RANDOM + $RANDOM ]
    col3=$[ $RANDOM + $RANDOM ]
    col4=$[ $RANDOM + $RANDOM ]

    bri1=$[ 50 + RANDOM % 200 ]
    bri2=$[ 50 + RANDOM % 200 ]
    bri3=$[ 50 + RANDOM % 200 ]
    bri4=$[ RANDOM % 100 ]

    #echo "col1: $col1, col2: $col2, bri1: $bri1, bri2: $bri2"
    light_hue 1 $col1 
    light_hue 2 $col2    
    light_hue 3 $col3
    light_hue 4 $col4
    light_hue 5 $col3
#    light_bri 1 $bri1
#    light_bri 2 $bri2
#    light_bri 3 $bri3
#    light_bri 4 $bri4
    sleep 5
done


