#!/bin/bash

source lights.conf

URL=http://$HUEIP/api/$SECRET/groups/0/action
PAYLOAD='{"bri": '$1', "transitiontime": 0}'

curl -s -H "Accept: application/json" -X PUT --data "$PAYLOAD" $URL > /dev/null
