#!/bin/bash

#acceptable values: 0 - 255

source lights.conf
LIGHTNUM=$1

URL=http://$HUEIP/api/$SECRET/lights/$1/state
PAYLOAD='{"sat": '$2', "transitiontime": 50}'

curl -H "Accept: application/json" -X PUT --data "$PAYLOAD" $URL > /dev/null
