#!/bin/bash

source lights.conf
LIGHTNUM=$1

URL=http://$HUEIP/api/$SECRET/groups/0/action
PAYLOAD='{"xy": ['"$1, $2"'], "transitiontime": '$TRANSTIME'}'
curl -s -H "Accept: application/json" -X PUT --data "$PAYLOAD" $URL > /dev/null
