#!/bin/bash
source lights.conf

SLEEPTIME=$(($TRANSTIME / 10))
SLEEPTIMELONG=$(($SLEEPTIME * 3))

lights_bri_notrans 1
sleep 1

while true
do
    lights_bri 254
    sleep $SLEEPTIME
    lights_bri 1
    sleep $SLEEPTIMELONG
done
