#!/bin/sh
#  script generated
#    on 2018-11-24 11:48:04 +0000
#    by kyb

#Light id 1 - Philips - LLC011 - LivingColors 1
light_on 1
light_hue 1 54000
light_sat 1 254
light_bri 1 254

#Light id 2 - Philips - LLC011 - LivingColors 2
light_on 2
light_hue 2 42000
light_sat 2 254
light_bri 2 254

#Light id 3 - Philips - LLC010 - Hue iris 1
light_on 3
light_hue 3 54000
light_sat 3 254
light_bri 3 254

#Light id 4 - Philips - LCT001 - Hue color lamp 1
light_on 4
light_hue 4 44000
light_sat 4 254
light_bri 4 254

#Light id 5 - Philips - LST001 - Hue lightstrip 1
light_on 5
light_hue 5 54000
light_sat 5 254
light_bri 5 254

#Light id 6 - Philips - LST002 - strippi
light_on 6
light_hue 6 42000
light_sat 6 254
light_bri 6 254

#Light id 7 - Philips - LST002 - deskstriptop
light_on 7
light_hue 7 42000
light_sat 7 254
light_bri 7 254

