#!/bin/sh
#  script generated
#    on 2018-09-30 08:47:03 +0000
#    by kyb

#Light id 1 - Philips - LLC011 - LivingColors 1
light_on 1
light_hue 1 8418
light_sat 1 0
light_bri 1 254

#Light id 2 - Philips - LLC011 - LivingColors 2
light_on 2
light_hue 2 8418
light_sat 2 0
light_bri 2 254

#Light id 3 - Philips - LLC010 - Hue iris 1
light_on 3
light_hue 3 8418
light_sat 3 0
light_bri 3 254

#Light id 4 - Philips - LCT001 - Hue color lamp 1
light_on 4
light_hue 4 20000
light_sat 4 140
light_bri 4 254

#Light id 5 - Philips - LST001 - Hue lightstrip 1
light_on 5
light_hue 5 8418
light_sat 5 0
light_bri 5 254

#Light id 6 - Philips - LST002 - strippi
light_on 6
light_hue 6 8418
light_sat 6 140
light_bri 6 254

