#!/bin/sh
#  script generated
#    on 2018-09-23 11:53:09 AM +0000
#    by kyb

#Light id 1 - Philips - LLC011 - LivingColors 1
light_on 1
light_hue 1 14000
light_sat 1 1
light_bri 1 254

#Light id 2 - Philips - LLC011 - LivingColors 2
light_on 2
light_hue 2 0
light_sat 2 0
light_bri 2 254

#Light id 3 - Philips - LLC010 - Hue iris 1
light_on 3
light_hue 3 0
light_sat 3 0
light_bri 3 254

#Light id 4 - Philips - LCT001 - Hue color lamp 1
light_on 4
light_hue 4 19000
light_sat 4 100
light_bri 4 254

#Light id 5 - Philips - LST001 - Hue lightstrip 1
light_on 5
light_hue 5 0
light_sat 5 0
light_bri 5 254

