#!/bin/sh
# this is a script which will dim/brighten your lights depending
# on your network bandwidth usage. the more you down/upload the 
# brighter your lights.
# interface and max bandwidth hardcoded, lol
lights_on
lights_sat 255
lights_bri 0
lights_off
light_on 1
light_on 2
light_on 3
light_on 5

_delta_t=1
_interface=en0
netstat -i -I ${_interface} -b -w ${_delta_t} |
    awk 'BEGIN {
    }{
        if ($0 !~ /(input|packets)/) {
            inb=$3 ; oub=$6 ;

            inbri=$3/1800000*255 ;
            oubri=$6/150000*255 ;

            printf("[%i, %i] ", inbri, oubri)

            system("lights_rx " int(inbri))
            system("lights_tx " int(oubri))
        }
    }'
